### PR TITLE
Added quote info link and Fulfilment Date  at transfer detail page

### PR DESCRIPTION
**Pull request by SithuKyaw-Thitsaworks**

### CODE REVIEW

**Review by pedrosousabarreto — APPROVED** [review]
Looks good to me.

**Comment by pedrosousabarreto** [comment]
Looks good to me, thank you for your first PR!
Please proceed with the merge.

**Comment by simeonoriko** [comment]
Congratulations on your first Mojaloop PR merge @SithuKyaw-Thitsaworks!

**Comment by elnyry-sam-k** [comment]
congratulations @SithuKyaw-Thitsaworks

**Pull request merged**
